name: "Build tests"
on:
  push:
    branches: [ master ]
jobs:
  linux_test_job:
    runs-on: ubuntu-latest
    name: Linux test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '20'
    - run: yarn install
    - run: yarn build
  mac_test_job:
    runs-on: macos-latest
    name: macOS test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '20'
    - run: yarn install
    - run: yarn build
  win_test_job:
    runs-on: windows-latest
    name: Windows test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '20'
    - run: yarn install
    - run: yarn build
